/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/3.0/athlete/programworkout/range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET range */
        get: {
            parameters: {
                query: {
                    startDate: string;
                    endDate: string;
                    preview?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            program_id?: number;
                            workout_id?: number;
                            workout_title?: string;
                            year?: number;
                            month?: number;
                            day?: number;
                            date?: string;
                            group_team_subscription_id?: Record<string, never> | null;
                            feed_item_id?: number;
                            summarizedSavedWorkout?: {
                                workout?: {
                                    id?: number;
                                    title?: string;
                                    instruction?: Record<string, never> | null;
                                    created_on?: string;
                                    updated_on?: string;
                                    workoutSets?: {
                                        id?: number;
                                        workout_id?: number;
                                        title?: string;
                                        phase?: number;
                                        order?: number;
                                        instruction?: string;
                                        is_test?: number;
                                        is_redzone?: number;
                                        test_instruction?: string;
                                        plain_text?: number;
                                        redzone_instruction?: string;
                                        redzone_type?: number;
                                        resets_working_max?: Record<string, never> | null;
                                        smaller_is_better?: Record<string, never> | null;
                                        source_id?: Record<string, never> | null;
                                        tracker_id?: Record<string, never> | null;
                                        updated_by?: Record<string, never> | null;
                                        updated_on?: Record<string, never> | null;
                                        workout_combo_id?: Record<string, never> | null;
                                        is_power?: number;
                                        is_speed?: number;
                                        is_agility?: number;
                                        is_endurance?: number;
                                        is_power_endurance?: number;
                                        is_strength?: number;
                                        test_type?: number;
                                        is_set?: number;
                                        type?: number;
                                        typeClass?: string;
                                        workoutSetExercises?: {
                                            id?: number;
                                            set_id?: number;
                                            exercise_id?: number;
                                            order?: number;
                                            title?: string;
                                            instruction?: string;
                                            no_sets?: number;
                                            param_1_type?: number;
                                            param_2_type?: number;
                                            param_1_data_1?: string;
                                            param_1_data_2?: string;
                                            param_1_data_3?: string;
                                            param_1_data_4?: string;
                                            param_1_data_5?: string;
                                            param_1_data_6?: string;
                                            param_1_data_7?: string;
                                            param_1_data_8?: string;
                                            param_1_data_9?: string;
                                            param_1_data_10?: string;
                                            param_2_data_1?: string;
                                            param_2_data_2?: string;
                                            param_2_data_3?: string;
                                            param_2_data_4?: string;
                                            param_2_data_5?: string;
                                            param_2_data_6?: string;
                                            param_2_data_7?: string;
                                            param_2_data_8?: string;
                                            param_2_data_9?: string;
                                            param_2_data_10?: string;
                                            reference_max_exercise_id?: number;
                                            workout_set_exercise_template_id?: Record<string, never> | null;
                                            param_count?: number;
                                            video_url?: string;
                                            video_thumbnail?: string;
                                        }[];
                                        exercises?: {
                                            id?: number;
                                            set_id?: number;
                                            exercise_id?: number;
                                            order?: number;
                                            title?: string;
                                            instruction?: string;
                                            no_sets?: number;
                                            param_1_type?: number;
                                            param_2_type?: number;
                                            param_1_data_1?: string;
                                            param_1_data_2?: string;
                                            param_1_data_3?: string;
                                            param_1_data_4?: string;
                                            param_1_data_5?: string;
                                            param_1_data_6?: string;
                                            param_1_data_7?: string;
                                            param_1_data_8?: string;
                                            param_1_data_9?: string;
                                            param_1_data_10?: string;
                                            param_2_data_1?: string;
                                            param_2_data_2?: string;
                                            param_2_data_3?: string;
                                            param_2_data_4?: string;
                                            param_2_data_5?: string;
                                            param_2_data_6?: string;
                                            param_2_data_7?: string;
                                            param_2_data_8?: string;
                                            param_2_data_9?: string;
                                            param_2_data_10?: string;
                                            reference_max_exercise_id?: number;
                                            workout_set_exercise_template_id?: Record<string, never> | null;
                                            param_count?: number;
                                            video_url?: string;
                                            video_thumbnail?: string;
                                        }[];
                                        block_title?: string;
                                    }[];
                                    exercises?: {
                                        id?: number;
                                        workout_id?: number;
                                        title?: string;
                                        phase?: number;
                                        order?: number;
                                        instruction?: string;
                                        is_test?: number;
                                        is_redzone?: number;
                                        test_instruction?: string;
                                        plain_text?: number;
                                        redzone_instruction?: string;
                                        redzone_type?: number;
                                        resets_working_max?: Record<string, never> | null;
                                        smaller_is_better?: Record<string, never> | null;
                                        source_id?: Record<string, never> | null;
                                        tracker_id?: Record<string, never> | null;
                                        updated_by?: Record<string, never> | null;
                                        updated_on?: Record<string, never> | null;
                                        workout_combo_id?: Record<string, never> | null;
                                        is_power?: number;
                                        is_speed?: number;
                                        is_agility?: number;
                                        is_endurance?: number;
                                        is_power_endurance?: number;
                                        is_strength?: number;
                                        test_type?: number;
                                        is_set?: number;
                                        type?: number;
                                        typeClass?: string;
                                        workoutSetExercises?: {
                                            id?: number;
                                            set_id?: number;
                                            exercise_id?: number;
                                            order?: number;
                                            title?: string;
                                            instruction?: string;
                                            no_sets?: number;
                                            param_1_type?: number;
                                            param_2_type?: number;
                                            param_1_data_1?: string;
                                            param_1_data_2?: string;
                                            param_1_data_3?: string;
                                            param_1_data_4?: string;
                                            param_1_data_5?: string;
                                            param_1_data_6?: string;
                                            param_1_data_7?: string;
                                            param_1_data_8?: string;
                                            param_1_data_9?: string;
                                            param_1_data_10?: string;
                                            param_2_data_1?: string;
                                            param_2_data_2?: string;
                                            param_2_data_3?: string;
                                            param_2_data_4?: string;
                                            param_2_data_5?: string;
                                            param_2_data_6?: string;
                                            param_2_data_7?: string;
                                            param_2_data_8?: string;
                                            param_2_data_9?: string;
                                            param_2_data_10?: string;
                                            reference_max_exercise_id?: number;
                                            workout_set_exercise_template_id?: Record<string, never> | null;
                                            param_count?: number;
                                            video_url?: string;
                                            video_thumbnail?: string;
                                        }[];
                                        exercises?: {
                                            id?: number;
                                            set_id?: number;
                                            exercise_id?: number;
                                            order?: number;
                                            title?: string;
                                            instruction?: string;
                                            no_sets?: number;
                                            param_1_type?: number;
                                            param_2_type?: number;
                                            param_1_data_1?: string;
                                            param_1_data_2?: string;
                                            param_1_data_3?: string;
                                            param_1_data_4?: string;
                                            param_1_data_5?: string;
                                            param_1_data_6?: string;
                                            param_1_data_7?: string;
                                            param_1_data_8?: string;
                                            param_1_data_9?: string;
                                            param_1_data_10?: string;
                                            param_2_data_1?: string;
                                            param_2_data_2?: string;
                                            param_2_data_3?: string;
                                            param_2_data_4?: string;
                                            param_2_data_5?: string;
                                            param_2_data_6?: string;
                                            param_2_data_7?: string;
                                            param_2_data_8?: string;
                                            param_2_data_9?: string;
                                            param_2_data_10?: string;
                                            reference_max_exercise_id?: number;
                                            workout_set_exercise_template_id?: Record<string, never> | null;
                                            param_count?: number;
                                            video_url?: string;
                                            video_thumbnail?: string;
                                        }[];
                                        block_title?: string;
                                    }[];
                                };
                                saved_workout?: {
                                    id?: number;
                                    user_id?: number;
                                    program_workout_id?: number;
                                    user_full_name?: string;
                                    name_last?: string;
                                    use_metric?: number;
                                    workout_id?: number;
                                    title?: string;
                                    instruction?: Record<string, never> | null;
                                    completed?: number;
                                    date_completed?: string;
                                    workout_rating?: string;
                                    notes?: string;
                                    status?: number;
                                    statusMessage?: string;
                                    version?: number;
                                    notes_on_feed?: number;
                                    percent_completed?: number;
                                    set_count?: number;
                                    rpe?: Record<string, never> | null;
                                    timestamp_updated?: number;
                                    timestamp_started?: number;
                                    timestamp_completed?: Record<string, never> | null;
                                    timestamp_rpe?: Record<string, never> | null;
                                    date_rescheduled?: Record<string, never> | null;
                                    addedWorkoutSets?: unknown[];
                                    workoutSets?: {
                                        id?: number;
                                        plain_text?: number;
                                        saved_workout_id?: number;
                                        workout_set_id?: number;
                                        title?: string;
                                        version?: number;
                                        is_super_set?: number;
                                        test_instruction?: string;
                                        is_power?: number;
                                        is_speed?: number;
                                        is_agility?: number;
                                        is_endurance?: number;
                                        is_power_endurance?: number;
                                        is_strength?: number;
                                        test_type?: number;
                                        test_data_1?: string;
                                        test_data_2?: string;
                                        this_workout_rz?: number;
                                        rx?: number;
                                        completed?: number;
                                        date_completed?: string;
                                        date_updated?: string;
                                        notes?: Record<string, never> | null;
                                        workout_percent_completed?: number;
                                        order?: number;
                                        phase?: number;
                                        exercise_count?: number;
                                        is_test?: number;
                                        instruction?: string;
                                        has_history?: boolean;
                                        workoutSetExercises?: {
                                            id?: number;
                                            saved_workout_set_id?: number;
                                            workout_set_exercise_id?: number;
                                            exercise_title?: string;
                                            exercise_id?: number;
                                            has_history?: boolean;
                                            notes?: Record<string, never> | null;
                                            instruction?: string;
                                            order?: number;
                                            no_sets?: number;
                                            tips?: string;
                                            prescribed_abr?: string;
                                            abr?: string;
                                            abr_kg?: string;
                                            abr_results?: string;
                                            video_url?: string;
                                            param_count?: number;
                                            completed?: number;
                                            param_1_type?: number;
                                            param_1_data_1?: string;
                                            param_1_made?: number;
                                            param_1_data_1_prescribed?: string;
                                            param_1_data_2?: string;
                                            param_2_made?: number;
                                            param_1_data_2_prescribed?: string;
                                            param_1_data_3?: string;
                                            param_3_made?: number;
                                            param_1_data_3_prescribed?: string;
                                            param_1_data_4?: string;
                                            param_4_made?: number;
                                            param_1_data_4_prescribed?: string;
                                            param_1_data_5?: string;
                                            param_5_made?: number;
                                            param_1_data_5_prescribed?: string;
                                            param_1_data_6?: string;
                                            param_6_made?: number;
                                            param_1_data_6_prescribed?: string;
                                            param_1_data_7?: string;
                                            param_7_made?: number;
                                            param_1_data_7_prescribed?: string;
                                            param_1_data_8?: string;
                                            param_8_made?: number;
                                            param_1_data_8_prescribed?: string;
                                            param_1_data_9?: string;
                                            param_9_made?: number;
                                            param_1_data_9_prescribed?: string;
                                            param_1_data_10?: string;
                                            param_10_made?: number;
                                            param_1_data_10_prescribed?: string;
                                            param_2_type?: number;
                                            param_2_data_1_prescribed?: string;
                                            param_2_data_1?: string;
                                            param_2_data_2_prescribed?: string;
                                            param_2_data_2?: string;
                                            param_2_data_3_prescribed?: string;
                                            param_2_data_3?: string;
                                            param_2_data_4_prescribed?: string;
                                            param_2_data_4?: string;
                                            param_2_data_5_prescribed?: string;
                                            param_2_data_5?: string;
                                            param_2_data_6_prescribed?: string;
                                            param_2_data_6?: string;
                                            param_2_data_7_prescribed?: string;
                                            param_2_data_7?: string;
                                            param_2_data_8_prescribed?: string;
                                            param_2_data_8?: string;
                                            param_2_data_9_prescribed?: string;
                                            param_2_data_9?: string;
                                            param_2_data_10_prescribed?: string;
                                            param_2_data_10?: string;
                                        }[];
                                    }[];
                                    team_title?: string;
                                    team_logo?: string;
                                    date_pretty?: string;
                                    is_in_compliance_mode?: boolean;
                                };
                                date?: string;
                            };
                            personal_cal?: boolean;
                            program_title?: string;
                            team_id?: number;
                            team_title?: string;
                            team_logo?: string;
                            team_org_id?: Record<string, never> | null;
                            coach_logo?: string;
                            comments?: {
                                streamId?: Record<string, never> | null;
                                lastActivityPreview?: Record<string, never> | null;
                                lastActivityUserPreview?: Record<string, never> | null;
                            };
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** POST auth */
        post: {
            parameters: {
                query?: {
                    t?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        email?: string;
                        password?: string;
                    };
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            api_token: string;
                            refresh_token?: string;
                            api_ttl?: number;
                            scope?: string;
                            role?: string;
                            session_id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/users/exercises": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET exercises */
        get: {
            parameters: {
                query: {
                    teamId: number;
                    userId: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            userId?: number;
                            title?: string;
                            logo?: string;
                            hasVideo?: boolean;
                            videoUrl?: string;
                            isCircuit?: boolean;
                            instructions?: string;
                            prescription?: string;
                            param1Type?: number;
                            param2Type?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/1.0/athlete/programming/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET programs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET users by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            date_of_birth?: string;
                            email?: string;
                            gender?: string;
                            gender_enum?: number;
                            height?: {
                                value?: number;
                                unit?: string;
                            };
                            image_avatar?: {
                                original_full_path?: string;
                                thumb_full_path?: string;
                            };
                            last_login?: string;
                            city?: Record<string, never> | null;
                            state?: Record<string, never> | null;
                            country?: Record<string, never> | null;
                            name_first?: string;
                            name_last?: string;
                            use_metric?: boolean;
                            username?: string;
                            weight?: {
                                value?: number;
                                unit?: string;
                            };
                            commitment_description?: string;
                            track_athlete_onboarding?: {
                                id?: number;
                                user_id?: number;
                                mobile_app_onboarding_flow_started_at?: string;
                                mobile_app_rating_given_at?: Record<string, never> | null;
                                mobile_app_rating_dismissed_at?: Record<string, never> | null;
                                mobile_profile_update_prompted_at?: string;
                                mobile_early_access_education_prompted_at?: Record<string, never> | null;
                                mobile_athlete_pro_trial_prompted_at?: string;
                                mobile_athlete_pro_trial_expiring_prompted_at?: string;
                            };
                            profile_validated?: string;
                            exclude_from_leaderboards?: Record<string, never> | null;
                            training_week_starts_on_monday?: boolean;
                            athleteTrial?: {
                                isInAthleteTrial?: boolean;
                                daysRemainingInAthleteTrial?: number;
                                hasExpiredAthleteTrial?: boolean;
                                expiresAtTimestamp?: Record<string, never> | null;
                            };
                            hasActiveAthleteProLicense?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/1.0/athlete/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET prefs */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            email_workout_preview?: number;
                            email_new_posts?: number;
                            email_coach_posts?: number;
                            email_like?: number;
                            email_comment?: number;
                            mobile_workout_preview?: number;
                            mobile_new_posts?: number;
                            mobile_coach_posts?: number;
                            mobile_like?: number;
                            mobile_comment?: number;
                            auto_update_wm?: number;
                            show_exercises_trainheroic?: number;
                            show_programs_trainheroic?: number;
                            show_calendars_trainheroic?: number;
                            show_workout_set_exercise_templates_trainheroic?: number;
                            survey_team_enabled?: number;
                            survey_one_to_one_enabled?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/2.0/athlete/workingMax": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET workingmax */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            uwm_id?: Record<string, never> | null;
                            exercise_id?: number;
                            title?: string;
                            param_type?: number;
                            value?: Record<string, never> | null;
                            created_on?: Record<string, never> | null;
                            type_suffix?: string;
                            working_max_id?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/1.0/athlete/savedworkoutset/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** PUT savedworkoutset by id */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {
                     *       "id": 1091463772,
                     *       "workoutSetId": 443115423,
                     *       "order": 2,
                     *       "isPlainText": false,
                     *       "title": "Strength/Power",
                     *       "isSuperSet": 0,
                     *       "comboId": null,
                     *       "version": 0,
                     *       "instruction": "",
                     *       "comboTitle": null,
                     *       "savedWorkoutSetExercises": [
                     *         {
                     *           "id": 1863781876,
                     *           "workoutSetExerciseId": 739137899,
                     *           "order": 1,
                     *           "instruction": "",
                     *           "completed": 0,
                     *           "title": "BARBELL BENCH PRESS",
                     *           "setCount": 1,
                     *           "tips": "",
                     *           "videoURL": "",
                     *           "notes": null,
                     *           "exerciseId": 1838251,
                     *           "param_1_type": 3,
                     *           "param_2_type": 1,
                     *           "version": null,
                     *           "abr": "1 set",
                     *           "param_1_made": 0,
                     *           "param_2_rx_1": "",
                     *           "param_1_data_1": "",
                     *           "param_2_data_1": "",
                     *           "param_2_made": 0,
                     *           "param_2_rx_2": "",
                     *           "param_1_data_2": "",
                     *           "param_2_data_2": "",
                     *           "param_3_made": 0,
                     *           "param_2_rx_3": "",
                     *           "param_1_data_3": "",
                     *           "param_2_data_3": "",
                     *           "param_4_made": 0,
                     *           "param_2_rx_4": "",
                     *           "param_1_data_4": "",
                     *           "param_2_data_4": "",
                     *           "param_5_made": 0,
                     *           "param_2_rx_5": "",
                     *           "param_1_data_5": "",
                     *           "param_2_data_5": "",
                     *           "param_6_made": 0,
                     *           "param_2_rx_6": "",
                     *           "param_1_data_6": "",
                     *           "param_2_data_6": "",
                     *           "param_7_made": 0,
                     *           "param_2_rx_7": "",
                     *           "param_1_data_7": "",
                     *           "param_2_data_7": "",
                     *           "param_8_made": 0,
                     *           "param_2_rx_8": "",
                     *           "param_1_data_8": "",
                     *           "param_2_data_8": "",
                     *           "param_9_made": 0,
                     *           "param_2_rx_9": "",
                     *           "param_1_data_9": "",
                     *           "param_2_data_9": "",
                     *           "param_10_made": 0,
                     *           "param_2_rx_10": "",
                     *           "param_1_data_10": "",
                     *           "param_2_data_10": ""
                     *         }
                     *       ],
                     *       "exercises": [
                     *         1863781876
                     *       ],
                     *       "sessionId": 239647907,
                     *       "saved": null,
                     *       "__completed": 0,
                     *       "completed": "0",
                     *       "__notes": null,
                     *       "notes": null
                     *     } */
                    "application/json": {
                        id?: number;
                        workoutSetId?: number;
                        order?: number;
                        isPlainText?: boolean;
                        title?: string;
                        isSuperSet?: number;
                        comboId?: Record<string, never> | null;
                        version?: number;
                        instruction?: string;
                        comboTitle?: Record<string, never> | null;
                        savedWorkoutSetExercises?: {
                            id?: number;
                            workoutSetExerciseId?: number;
                            order?: number;
                            instruction?: string;
                            completed?: number;
                            title?: string;
                            setCount?: number;
                            tips?: string;
                            videoURL?: string;
                            notes?: Record<string, never> | null;
                            exerciseId?: number;
                            param_1_type?: number;
                            param_2_type?: number;
                            version?: Record<string, never> | null;
                            abr?: string;
                            param_1_made?: number;
                            param_2_rx_1?: string;
                            param_1_data_1?: string;
                            param_2_data_1?: string;
                            param_2_made?: number;
                            param_2_rx_2?: string;
                            param_1_data_2?: string;
                            param_2_data_2?: string;
                            param_3_made?: number;
                            param_2_rx_3?: string;
                            param_1_data_3?: string;
                            param_2_data_3?: string;
                            param_4_made?: number;
                            param_2_rx_4?: string;
                            param_1_data_4?: string;
                            param_2_data_4?: string;
                            param_5_made?: number;
                            param_2_rx_5?: string;
                            param_1_data_5?: string;
                            param_2_data_5?: string;
                            param_6_made?: number;
                            param_2_rx_6?: string;
                            param_1_data_6?: string;
                            param_2_data_6?: string;
                            param_7_made?: number;
                            param_2_rx_7?: string;
                            param_1_data_7?: string;
                            param_2_data_7?: string;
                            param_8_made?: number;
                            param_2_rx_8?: string;
                            param_1_data_8?: string;
                            param_2_data_8?: string;
                            param_9_made?: number;
                            param_2_rx_9?: string;
                            param_1_data_9?: string;
                            param_2_data_9?: string;
                            param_10_made?: number;
                            param_2_rx_10?: string;
                            param_1_data_10?: string;
                            param_2_data_10?: string;
                        }[];
                        exercises?: number[];
                        sessionId?: number;
                        saved?: Record<string, never> | null;
                        __completed?: number;
                        completed?: string;
                        __notes?: Record<string, never> | null;
                        notes?: Record<string, never> | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/1.0/user/userInfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET userinfo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            username?: string;
                            email?: string;
                            name_first?: string;
                            name_last?: string;
                            dob?: string;
                            gender?: number;
                            use_metric?: boolean;
                            height?: Record<string, never> | null;
                            weight?: number;
                            country?: Record<string, never> | null;
                            state?: Record<string, never> | null;
                            city?: Record<string, never> | null;
                            phone?: Record<string, never> | null;
                            phone_os?: Record<string, never> | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/1.0/athlete/savedworkout/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** PUT savedworkout by id */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    /** @example {
                     *       "id": 1739724922876,
                     *       "date": "2025-02-16T00:00:00.000Z",
                     *       "programTitle": "",
                     *       "workoutId": 0,
                     *       "programWorkoutId": 0,
                     *       "preWorkoutSurvey": null,
                     *       "feedItem": null,
                     *       "instruction": "",
                     *       "version": 0,
                     *       "publicNotes": "",
                     *       "startedAt": null,
                     *       "endedAt": null,
                     *       "comments": null,
                     *       "lastUserComments": null,
                     *       "streamId": null,
                     *       "blocks": [],
                     *       "isLocalToDevice": true,
                     *       "prescribedDateString": "2025-02-16",
                     *       "teamOrgId": null,
                     *       "isPersonalCalendar": true,
                     *       "teamId": 594128,
                     *       "teamLogo": "https://static.trainheroic.com/avatar/avatar-AC-54d1cf911bbbb8dc63eaf4088ddab264.png",
                     *       "title": "2025-02-16",
                     *       "useMetric": false,
                     *       "dateString": "2025-02-16",
                     *       "saved": null,
                     *       "__completed": false,
                     *       "completed": "0",
                     *       "__completionDuration": null,
                     *       "completionDuration": null,
                     *       "__rpe": null,
                     *       "rpe": null
                     *     } */
                    "application/json": {
                        id?: number;
                        date?: string;
                        programTitle?: string;
                        workoutId?: number;
                        programWorkoutId?: number;
                        preWorkoutSurvey?: Record<string, never> | null;
                        feedItem?: Record<string, never> | null;
                        instruction?: string;
                        version?: number;
                        publicNotes?: string;
                        startedAt?: Record<string, never> | null;
                        endedAt?: Record<string, never> | null;
                        comments?: Record<string, never> | null;
                        lastUserComments?: Record<string, never> | null;
                        streamId?: Record<string, never> | null;
                        blocks?: unknown[];
                        isLocalToDevice?: boolean;
                        prescribedDateString?: string;
                        teamOrgId?: Record<string, never> | null;
                        isPersonalCalendar?: boolean;
                        teamId?: number;
                        teamLogo?: string;
                        title?: string;
                        useMetric?: boolean;
                        dateString?: string;
                        saved?: Record<string, never> | null;
                        __completed?: boolean;
                        completed?: string;
                        __completionDuration?: Record<string, never> | null;
                        completionDuration?: Record<string, never> | null;
                        __rpe?: Record<string, never> | null;
                        rpe?: Record<string, never> | null;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/calendars/athletes/{id}/coachAthleteTeam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET coachathleteteam by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            title?: string;
                            logo?: string;
                            owner_user_id?: number;
                            id?: number;
                            athlete_id?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/users/444862/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET features */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            user_id?: number;
                            features?: {
                                parental_consent_v2?: boolean;
                                account_creation_rate_limit?: boolean;
                                avalara_tax_integration_v1?: boolean;
                                mobile_account_creation_hcaptcha?: boolean;
                                best_practice_example?: boolean;
                                mobile_admin?: boolean;
                                mobile_admin_login_as?: boolean;
                                mobile_admin_forced_update_test?: boolean;
                                mobile_past_performances_lifts_v1?: boolean;
                                mobile_past_performances_circuits_v1?: boolean;
                                mobile_athlete_profile_v1?: boolean;
                                mobile_athlete_onboarding_personalization_v1?: boolean;
                                mobile_notification_channels_v1?: boolean;
                                web_notifications?: boolean;
                                mobile_notification_center_v1?: boolean;
                                web_notification_center_v1?: boolean;
                                mobile_push_notifications?: boolean;
                                email_notifications?: boolean;
                                complete_session_reminder_notifications?: boolean;
                                session_complete_one_to_one?: boolean;
                                mobile_add_remove_set?: boolean;
                                mobile_logging_view_2019_v1?: boolean;
                                mobile_session_reschedule_v1?: boolean;
                                mobile_exercise_swap_v1?: boolean;
                                mobile_rate_this_app?: boolean;
                                api_session_reschedule?: boolean;
                                mobile_add_exercise_v2?: boolean;
                                api_add_remove_exercise?: boolean;
                                api_exercise_swap?: boolean;
                                api_last_performance?: boolean;
                                mobile_messaging_v1?: boolean;
                                mobile_messaging_gif_v1?: boolean;
                                mobile_messaging_reactions_v1?: boolean;
                                mobile_messaging_video_v1?: boolean;
                                web_messaging_v1?: boolean;
                                marketplace_payment_confirmation?: boolean;
                                marketplace_checkout?: boolean;
                                mobile_iap_v1?: boolean;
                                mobile_calculator_v2?: boolean;
                                mobile_exercise_history_v1?: boolean;
                                mobile_exercise_stats?: boolean;
                                mobile_athlete_create_session_v1?: boolean;
                                mobile_athlete_copy_paste_session?: boolean;
                                mobile_athlete_create_exercise_v1?: boolean;
                                mobile_athlete_add_parameter_gold_team?: boolean;
                                mobile_onboarding_profile_image_upload_black_team?: boolean;
                                mobile_onboarding_profile_image_upload_gold_team?: boolean;
                                mobile_athlete_custom_timer_v1?: boolean;
                                mobile_athlete_tabata_v1?: boolean;
                                mobile_athlete_emom_v1?: boolean;
                                mobile_athlete_amrap_v1?: boolean;
                                mobile_athlete_for_time_v1?: boolean;
                                mobile_athlete_custom_interval_v1?: boolean;
                                marketplace_shop_settings?: boolean;
                                mobile_create_circuit?: boolean;
                                mobile_circuit_notes?: boolean;
                                mobile_exercise_history_no_date_limit_v2?: boolean;
                                mobile_exercise_history_editable_v1?: boolean;
                                mobile_app_review_v1?: boolean;
                                athlete_profile_prompts_v1?: boolean;
                                training_week_starts_monday?: boolean;
                                logging_keyboard_v2?: boolean;
                                library_menu_item_v2?: boolean;
                                library_nav_v2?: boolean;
                                mobile_onboarding_reduced_flow_gold_team?: boolean;
                                mobile_library_manage_circuits_exercises_v2?: boolean;
                                library_create_session_template_v3?: boolean;
                                new_iap_teams_v1?: boolean;
                                working_maxes_by_reference_exercise_v1?: boolean;
                                programming_keyboard_v2?: boolean;
                                coach_library_v3?: boolean;
                                mobile_user_delete_v1?: boolean;
                                notification_settings_reset_v1?: boolean;
                                year_in_review_v1?: boolean;
                                year_in_review_v3?: boolean;
                                year_in_review_v4?: boolean;
                                bundle_th_fee_increase_v1?: boolean;
                                api_fetch_range_filter_deleted_personal_calendar_subscriptions_v1?: boolean;
                                completed_exercise_history_v1?: boolean;
                                exercise_history_stackup_v2?: boolean;
                                estimated_1rm_graph_date_filter_v1?: boolean;
                                actual_rep_max_graph_v1?: boolean;
                                mobile_android_audio_background_service_v1?: boolean;
                                eppo_implementation_v1?: boolean;
                                mobile_coach_log_for_athlete?: boolean;
                                mobile_coach_programming_v1?: boolean;
                                mobile_coach_programming_v3?: boolean;
                                mobile_coach_publish?: boolean;
                                mobile_coach_create_team_v1?: boolean;
                                mobile_coach_invite_athlete_v1?: boolean;
                                mobile_coach_home_v1?: boolean;
                                web_coach_home?: boolean;
                                coach_pricing?: boolean;
                                marketplace_editor?: boolean;
                                mobile_low_programming?: boolean;
                                missed_sessions?: boolean;
                                coach_allow_athlete_trials?: boolean;
                                mobile_coach_programming_with_gestures?: boolean;
                                mobile_coach_create_exercise_v1?: boolean;
                                coach_library_v2?: boolean;
                                logging_personal_records_celebration_v2?: boolean;
                                athlete_pro_upgrade_v2?: boolean;
                                mobile_athlete_pro_v2?: boolean;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/users/exercises/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id: number;
                            userId: number;
                            title: string;
                            logo?: string;
                            hasVideo?: boolean;
                            videoUrl?: string;
                            isCircuit?: boolean;
                            instructions?: string;
                            prescription?: string;
                            param1Type?: number;
                            param2Type?: Record<string, never> | null;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/users/exercises/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET recent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            userId?: number;
                            title?: string;
                            logo?: string;
                            hasVideo?: boolean;
                            videoUrl?: string;
                            isCircuit?: boolean;
                            instructions?: string;
                            prescription?: string;
                            param1Type?: number;
                            param2Type?: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/users/circuits/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET recent */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/programs/new": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET new */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/users/circuits/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET history */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            userId?: number;
                            title?: string;
                            logo?: string;
                            isCircuit?: boolean;
                            instructions?: string;
                            prescription?: string;
                            leaderboard?: number;
                            exerciseIds?: unknown[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/exercises/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET history by id */
        get: {
            parameters: {
                query: {
                    userId: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            liftPRs?: {
                                weight?: number;
                                savedWorkoutSetExerciseId?: number;
                                setNumber?: number;
                                dateCompleted?: string;
                                reps?: number;
                                units?: string;
                                isMetric?: boolean;
                                description?: string;
                            }[];
                            singleParamPRs?: unknown[];
                            history?: {
                                dateCompleted?: string;
                                notes?: Record<string, never> | null;
                                isLift?: boolean;
                                param1Type?: number;
                                param2Type?: number;
                                savedWorkoutSetExerciseId?: number;
                                teamId?: number;
                                programWorkoutId?: number;
                                abr?: string;
                                bestEstimated1RM?: number;
                                repMaxes?: {
                                    reps?: number;
                                    weight?: number;
                                }[];
                                sets?: {
                                    setNumber?: number;
                                    formattedValue?: string;
                                    rawValue1?: number;
                                    rawValue2?: number;
                                    savedWorkoutSetExerciseId?: number;
                                }[];
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/exercises/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET exercises by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            description?: string;
                            pointsOfPerformance?: string;
                            param1Type?: number;
                            param2Type?: number;
                            icon?: Record<string, never> | null;
                            title?: string;
                            thumbnailUrl?: string;
                            userId?: number;
                            videoUrl?: string;
                            isLift?: boolean;
                            isSingleParam?: boolean;
                            units?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/users/{id}/workingMaxes/{id1}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET workingmaxes by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    id1: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            value?: number;
                            hasReferenceMaxExercise?: boolean;
                            referenceMaxExercise?: Record<string, never> | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/programs/free": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET free */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            teamId?: number;
                            teamDifficulty?: string;
                            title?: string;
                            description?: string;
                            logo?: string;
                            lengthWeeks?: number;
                            programWorkouts?: {
                                id?: number;
                                date?: string;
                                timelineDay?: number;
                                isSubscription?: boolean;
                                published?: boolean;
                                workoutTitle?: string;
                                workout?: {
                                    id?: number;
                                    title?: string;
                                    instruction?: string;
                                    timestampCreated?: number;
                                    workoutSets?: {
                                        id?: number;
                                        title?: string;
                                        instruction?: string;
                                        order?: number;
                                        isLeaderboard?: number;
                                        leaderboardInstructions?: string;
                                        leaderboardType?: number;
                                        isCircuit?: boolean;
                                        circuitId?: Record<string, never> | null;
                                        circuitTitle?: Record<string, never> | null;
                                        workoutSetExercises?: {
                                            id?: number;
                                            workoutSetId?: number;
                                            instruction?: string;
                                            order?: number;
                                            setCount?: number;
                                            param1Type?: number;
                                            param2Type?: number;
                                            param1Data1?: string;
                                            param1Data2?: string;
                                            param1Data3?: string;
                                            param1Data4?: string;
                                            param1Data5?: string;
                                            param1Data6?: string;
                                            param1Data7?: string;
                                            param1Data8?: string;
                                            param1Data9?: string;
                                            param1Data10?: string;
                                            param2Data1?: string;
                                            param2Data2?: string;
                                            param2Data3?: string;
                                            param2Data4?: string;
                                            param2Data5?: string;
                                            param2Data6?: string;
                                            param2Data7?: string;
                                            param2Data8?: string;
                                            param2Data9?: string;
                                            param2Data10?: string;
                                            exercise?: {
                                                id?: number;
                                                title?: string;
                                                videoUrl?: string;
                                            };
                                        }[];
                                    }[];
                                };
                            }[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/athleteProfile/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET summary */
        get: {
            parameters: {
                query: {
                    user_id: number;
                    use_metric?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            reps_sum?: number;
                            volume_sum?: number;
                            sessions_count?: number;
                            first_logged_date?: string;
                            last_logged_date?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/3.0/athlete/leaderboard/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET leaderboard by id */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    pageSize?: number;
                    gender?: number;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            workoutId?: number;
                            workoutTitle?: string;
                            date?: string;
                            timestamp?: number;
                            tests?: {
                                title?: string;
                                testType?: number;
                                testInstructions?: string;
                                unit?: string;
                                workoutSetId?: number;
                            }[];
                            results?: unknown[];
                            testStats?: {
                                avg?: number;
                                cnt?: number;
                            }[];
                            userResult?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/exercises/{id}/personalRecords": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET personalrecords by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/exercises/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET stats by id */
        get: {
            parameters: {
                query: {
                    userId: number;
                    date?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            isLift?: boolean;
                            lastPerformance?: Record<string, never> | null;
                            personalRecord?: Record<string, never> | null;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v5/exercises/{id}/stackUp/isSupportedExercise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET issupportedexercise by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            isSupportedExercise?: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
